CrossoverStockExchange/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrossoverStockExchange.Core.Services.Abstract;
using CrossoverStockExchange.Core.Services.Concrete;
using CrossoverStockExchange.Core.Entities;
using Microsoft.AspNet.Identity;
namespace CrossoverStockExchange.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        private readonly IStockExchangeService stockExchangeService;
        public StockController(IStockExchangeService stockExchangeService)
        {
            this.stockExchangeService = stockExchangeService;
        }
        // GET: Stock
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            StockExchangeWebService.StockExchangeWebService ws = new StockExchangeWebService.StockExchangeWebService();
            var res = ws.GetAllStock();
            return View(Helper.StockExchangeHelper.ConvertToPlainStock(res));
        }
        public ActionResult Details(string Code)
        {

            return View();
        }
        public ActionResult Find()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Find(Models.StockViewModels.Find stockFinder)
        {
            if (ModelState.IsValid)
            {
                stockFinder.stock = stockExchangeService.FindByCode(stockFinder.Code);
            }
            return View(stockFinder);
        }

        public ActionResult Add(int id)
        {
            stockExchangeService.AddStockToUserList(id, User.Identity.GetUserId());
            // add feedback
            return RedirectToAction("List");
        }
    }
}

CrossoverStockExchange/Controllers/UserStockExchangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrossoverStockExchange.Core.Services.Abstract;
using CrossoverStockExchange.Core.Services.Concrete;
using CrossoverStockExchange.Core.Entities;
using Microsoft.AspNet.Identity;

namespace CrossoverStockExchange.Controllers
{
    [Authorize]
    public class UserStockExchangeController : Controller
    {
        private readonly IStockExchangeService stockExchangeService;
        private readonly IUserService userService;

        public UserStockExchangeController(IStockExchangeService stockExchangeService, IUserService userService)
        {
            this.userService = userService;
            this.stockExchangeService = stockExchangeService;
        }

        // GET: UserStockExchange
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            StockExchangeWebService.StockExchangeWebService ws = new StockExchangeWebService.StockExchangeWebService();

            var user = userService.GetById(User.Identity.GetUserId());
            var Codes = user.UserStock.Select(x => x.Code).ToList();

            var res = ws.GetAllStockByCodeList(Codes.ToArray());
            
            Models.UserStockExchange.List model = new Models.UserStockExchange.List();
            model.UserName = user.UserName;
            model.StockList = Helper.StockExchangeHelper.ConvertToPlainStock(res);
            return View(model);
        }
      

        public ActionResult remove(int id)
        {
           bool res = stockExchangeService.RemoveStockExchangeFromUser(id, User.Identity.GetUserId());
            //add feedback
           return RedirectToAction("List");
        }
    }
}

CrossoverStockExchange/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crossover Stock Exchange</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Crossover Stock Exchange", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("All Stock exchanges", "List", "Stock")</li>
                    <li>@Html.ActionLink("My list of stock exchanges", "List", "UserStockExchange")</li>
                    <li>@Html.ActionLink("Find stock exchange", "Find", "Stock")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> :) 2016-01-18</p>
            <!-- OH you found me!
            Have so fun
                http://www.sanger.dk/
                -->
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>